name: Build and Release Rustdesk Installer

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x' # Stay on .NET 9

      - name: Modify Configuration.cs
        env:
          RUSTDESK_CONFIG: ${{ secrets.RUSTDESK_CONFIG }}
          RUSTDESK_PASSWORD: ${{ secrets.RUSTDESK_PASSWORD }}
        run: |
          $configFile = ".\\RustdeskSetup\\Configuration.cs"
          (Get-Content $configFile) -replace 'internal static string RustdeskCfg { get; set; } = DefaultConfigValue;', "internal static string RustdeskCfg { get; set; } = '$env:RUSTDESK_CONFIG';" `
          -replace 'internal static string RustdeskPw { get; set; } = DefaultPasswordValue;', "internal static string RustdeskPw { get; set; } = '$env:RUSTDESK_PASSWORD';" |
          Set-Content $configFile

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Publish project
        run: dotnet publish --configuration Release --output publish

      - name: Decode and Save PFX Certificate
        env:
          CODE_SIGNING_CERTIFICATE: ${{ secrets.CODE_SIGNING_CERTIFICATE }}
        run: |
          [System.Convert]::FromBase64String("$env:CODE_SIGNING_CERTIFICATE") | Set-Content -Path "codesigning.pfx" -Encoding Byte

      - name: Verify Certificate File
        run: |
          if (!(Test-Path "codesigning.pfx")) { 
            Write-Host "Certificate file not found!" 
            exit 1 
          }

      - name: Sign the Executable
        env:
          CODE_SIGNING_CERTIFICATE_PASSWORD: ${{ secrets.CODE_SIGNING_CERTIFICATE_PASSWORD }}
        run: |
          & "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\signtool.exe" sign /f codesigning.pfx /p "$env:CODE_SIGNING_CERTIFICATE_PASSWORD" /t http://timestamp.digicert.com /v publish\RustdeskSetup.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-installer
          path: publish

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_id }}
          release_name: Release ${{ github.run_id }}
          body: |
            Rustdesk installer build ${{ github.run_id }}.
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: publish/RustdeskSetup.exe
          asset_name: RustdeskSetup.exe
          asset_content_type: application/octet-stream
