name: Build Rustdesk Installers

on:
  workflow_call:  # Allows execution when called by master.yml
  workflow_run:
    workflows: ["Prepare Build Environment"]
    types:
      - completed

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [default, jeff]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Prepared Artifacts
        uses: actions/download-artifact@v4
        with:
          name: prep-artifacts
          path: .

      - name: Modify Configuration.cs (Jeff)
        env:
          RUSTDESK_CONFIG: ${{ secrets.RUSTDESK_CONFIG }}
          RUSTDESK_PASSWORD: ${{ secrets.RUSTDESK_PASSWORD }}
        run: |
          $configValue = ""
          $passwordValue = ""

          if ("${{ matrix.build_type }}" -eq "jeff") {
            $configValue = "private const string DefaultConfigValue = `"$env:RUSTDESK_CONFIG`";"
            $passwordValue = "private const string DefaultPasswordValue = `"$env:RUSTDESK_PASSWORD`";"
          } else {
            $configValue = 'private const string DefaultConfigValue = "";'
            $passwordValue = 'private const string DefaultPasswordValue = "";'
          }

          (Get-Content Configuration.cs) -replace 'private const string DefaultConfigValue = "";', $configValue | Set-Content Configuration.cs
          (Get-Content Configuration.cs) -replace 'private const string DefaultPasswordValue = "";', $passwordValue | Set-Content Configuration.cs
        shell: pwsh

      - name: Restore dependencies
        run: dotnet restore "rustdesk-setup.csproj"

      - name: Build project
        run: >-
          dotnet build "rustdesk-setup.csproj" --configuration Release
          --no-restore

      - name: Publish project
        run: >-
          dotnet publish "rustdesk-setup.csproj" --configuration Release
          --output publish --no-build

      - name: Rename Default Executable (for default build)
        if: matrix.build_type == 'default'
        shell: pwsh
        run: |
          Rename-Item -Path "publish/rustdesk-setup.exe" -NewName "rustdesk-setup.exe"

      - name: Rename Jeff Executable (for jeff build)
        if: matrix.build_type == 'jeff'
        shell: pwsh
        run: |
          Rename-Item -Path "publish/rustdesk-setup.exe" -NewName "rustdesk-setup-jeff.exe"

      - name: Upload Built Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'rustdesk-installer-${{ matrix.build_type }}'
          path: 'publish/*.exe'
