name: 0 - Full Rustdesk Build and Release

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  prep:
    uses: ./.github/workflows/prep.yml

  build:
    needs: prep
    uses: ./.github/workflows/build.yml
    secrets: inherit  # Pass all secrets automatically to build.yml

  sign:
    needs: build
    uses: ./.github/workflows/sign.yml
    secrets: inherit  # Ensure secrets are passed for signing

  release:
    needs: sign
    uses: ./.github/workflows/release.yml
    secrets: inherit  # Ensure secrets are passed for releasing
