name: Full Rustdesk Build and Release

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  prep:
    uses: ./.github/workflows/prep.yml

  build:
    needs: prep
    uses: ./.github/workflows/build.yml

  sign:
    needs: build
    uses: ./.github/workflows/sign.yml  # Call the new sign workflow after build
    with:  # Pass secrets as inputs to the called workflow
      CODE_SIGNING_CERTIFICATE: ${{ secrets.CODE_SIGNING_CERTIFICATE }}
      CODE_SIGNING_CERTIFICATE_PASSWORD: ${{ secrets.CODE_SIGNING_CERTIFICATE_PASSWORD }}

  release:
    needs: sign
    uses: ./.github/workflows/release.yml  # Call the new release workflow after sign
