name: Full Rustdesk Build and Release

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  full_build_default:
    runs-on: windows-latest
    outputs:
      formatted_time: ${{ steps.timestamp.outputs.formatted_time }}
      formatted_time2: ${{ steps.timestamp.outputs.formatted_time2 }}
    steps:
      - name: Validate Required Secrets
        run: |
          $missing = @()
          if (-not "${{ secrets.RUSTDESK_CONFIG }}") { $missing += "RUSTDESK_CONFIG" }
          if (-not "${{ secrets.RUSTDESK_PASSWORD }}") { $missing += "RUSTDESK_PASSWORD" }
          if (-not "${{ secrets.CODE_SIGNING_CERTIFICATE }}") { $missing += "CODE_SIGNING_CERTIFICATE" }
          if (-not "${{ secrets.CODE_SIGNING_CERTIFICATE_PASSWORD }}") { $missing += "CODE_SIGNING_CERTIFICATE_PASSWORD" }
          if (-not "${{ secrets.GITHUB_TOKEN }}") { $missing += "GITHUB_TOKEN" }

          if ($missing.Count -gt 0) {
            Write-Host "❌ Missing required secrets: $($missing -join ', ')"
            exit 1
          } else {
            Write-Host "✅ All required secrets are set!"
          }
        shell: pwsh

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Get Chicago Timestamp
        id: timestamp
        run: |
          $chicagoTimeZone = [System.TimeZoneInfo]::FindSystemTimeZoneById("Central Standard Time")
          $chicagoTime = [System.TimeZoneInfo]::ConvertTimeFromUtc((Get-Date).ToUniversalTime(), $chicagoTimeZone)
          
          $formatted_time = $chicagoTime.ToString("yyyy.MM.dd.HHmm")
          $formatted_time2 = $chicagoTime.ToString("yyyy.MM.dd")

          echo "formatted_time=$formatted_time" >> $GITHUB_ENV
          echo "formatted_time2=$formatted_time2" >> $GITHUB_ENV

          echo "formatted_time=$formatted_time" >> $GITHUB_ENV
          echo "formatted_time2=$formatted_time2" >> $GITHUB_ENV

      - name: Modify rustdesk-setup.csproj for Versioning (Default)
        run: |
          $projectFile = "rustdesk-setup.csproj"
          [xml]$xml = Get-Content $projectFile
          
          $propGroup = $xml.Project.PropertyGroup
          if ($propGroup -eq $null) {
            $propGroup = $xml.CreateElement("PropertyGroup")
            $xml.Project.AppendChild($propGroup)
          }

          # Create or update AssemblyVersion element
          $assemblyVersionElement = $propGroup.SelectSingleNode("AssemblyVersion")
          if ($assemblyVersionElement -eq $null) {
              $assemblyVersionElement = $xml.CreateElement("AssemblyVersion")
              $propGroup.AppendChild($assemblyVersionElement)
          }
          $assemblyVersionElement.InnerText = "${{ env.formatted_time }}"

           # Create or update FileVersion element
          $fileVersionElement = $propGroup.SelectSingleNode("FileVersion")
          if ($fileVersionElement -eq $null) {
              $fileVersionElement = $xml.CreateElement("FileVersion")
              $propGroup.AppendChild($fileVersionElement)
          }
          $fileVersionElement.InnerText = "${{ env.formatted_time }}"

          # Create or update Version element
          $versionElement = $propGroup.SelectSingleNode("Version")
           if ($versionElement -eq $null) {
              $versionElement = $xml.CreateElement("Version")
              $propGroup.AppendChild($versionElement)
          }
          $versionElement.InnerText = "${{ env.formatted_time2 }}"

          $xml.Save($projectFile)
        shell: pwsh

      - name: Restore dependencies
        run: dotnet restore "rustdesk-setup.csproj"

      - name: Build & Publish (Default)
        run: |
          dotnet publish "rustdesk-setup.csproj" --configuration Release --output "publish" --no-restore
          Rename-Item -Path "publish/rustdesk-setup.exe" -NewName "rustdesk-setup.exe"
        shell: pwsh

      - name: Upload Built Default Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-installer-default
          path: publish/rustdesk-setup.exe

  full_build_jeff:
    runs-on: windows-latest
    needs: full_build_default
    env:
      RUSTDESK_CONFIG: ${{ secrets.RUSTDESK_CONFIG }}
      RUSTDESK_PASSWORD: ${{ secrets.RUSTDESK_PASSWORD }}
      FORMATTED_TIME: ${{ needs.full_build_default.outputs.formatted_time }}
      FORMATTED_TIME2: ${{ needs.full_build_default.outputs.formatted_time2 }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Modify Configuration.cs (Jeff)
        run: |
          (Get-Content "Configuration.cs") -replace 'private const string DefaultConfigValue = .*;', "private const string DefaultConfigValue = `"$env:RUSTDESK_CONFIG`";" |
          Set-Content "Configuration.cs"
        shell: pwsh

      - name: Modify rustdesk-setup.csproj for Versioning (Jeff)
        run: |
          $projectFile = "rustdesk-setup.csproj"
          [xml]$xml = Get-Content $projectFile
          
          $propGroup = $xml.Project.PropertyGroup
          if ($propGroup -eq $null) {
            $propGroup = $xml.CreateElement("PropertyGroup")
            $xml.Project.AppendChild($propGroup)
          }

          # Create or update AssemblyVersion element
          $assemblyVersionElement = $propGroup.SelectSingleNode("AssemblyVersion")
          if ($assemblyVersionElement -eq $null) {
              $assemblyVersionElement = $xml.CreateElement("AssemblyVersion")
              $propGroup.AppendChild($assemblyVersionElement)
          }
          $assemblyVersionElement.InnerText = "${{ env.formatted_time }}"

           # Create or update FileVersion element
          $fileVersionElement = $propGroup.SelectSingleNode("FileVersion")
          if ($fileVersionElement -eq $null) {
              $fileVersionElement = $xml.CreateElement("FileVersion")
              $propGroup.AppendChild($fileVersionElement)
          }
          $fileVersionElement.InnerText = "${{ env.formatted_time }}"

          # Create or update Version element
          $versionElement = $propGroup.SelectSingleNode("Version")
           if ($versionElement -eq $null) {
              $versionElement = $xml.CreateElement("Version")
              $propGroup.AppendChild($versionElement)
          }
          $versionElement.InnerText = "${{ env.formatted_time2 }}"

          $xml.Save($projectFile)
        shell: pwsh

      - name: Restore dependencies
        run: dotnet restore "rustdesk-setup.csproj"

      - name: Build & Publish (Jeff)
        run: |
          dotnet publish "rustdesk-setup.csproj" --configuration Release --output "publish" --no-restore
          Rename-Item -Path "publish/rustdesk-setup.exe" -NewName "rustdesk-setup-jeff.exe"
        shell: pwsh

      - name: Upload Built Jeff Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-installer-jeff
          path: publish/rustdesk-setup-jeff.exe

  sign_and_release:
    runs-on: windows-latest
    needs: [full_build_default, full_build_jeff]
    steps:
    
      - name: Download Built Artifacts
        uses: actions/download-artifact@v4
        with:
          name: rustdesk-installer-default
          path: artifacts/default

      - name: Download Jeff Build
        uses: actions/download-artifact@v4
        with:
          name: rustdesk-installer-jeff
          path: artifacts/jeff

      - name: Locate signtool.exe
        id: find_signtool
        run: |
          $possiblePaths = @(
            "C:\Program Files (x86)\Windows Kits\10\bin\x64\signtool.exe",
            "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\signtool.exe",
            "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x64\signtool.exe",
            "C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\signtool.exe",
            "C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\signtool.exe",
            "C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64\signtool.exe",
            "C:\Program Files (x86)\Windows Kits\10\bin\10.0.17134.0\x64\signtool.exe",
            "C:\Program Files (x86)\Windows Kits\10\bin\10.0.16299.0\x64\signtool.exe",
            "C:\Program Files (x86)\Windows Kits\10\bin\10.0.15063.0\x64\signtool.exe",
            "C:\Program Files (x86)\Windows Kits\10\bin\10.0.14393.0\x64\signtool.exe",
            "C:\Program Files (x86)\Windows Kits\10\bin\10.0.10586.0\x64\signtool.exe",
            "C:\Program Files (x86)\Windows Kits\10\bin\10.0.10240.0\x64\signtool.exe"
          )

          $signtoolPath = $null
          foreach ($path in $possiblePaths) {
            if (Test-Path $path) {
              $signtoolPath = $path
              break
            }
          }

          if (-not $signtoolPath) {
            Write-Host "❌ signtool.exe not found in common locations."
            exit 1
          }

          echo "::set-output name=signtool_path::$signtoolPath"
        shell: pwsh

      - name: Sign Executables
        run: |
          Get-ChildItem -Path "artifacts" -Filter "*.exe" | ForEach-Object {
            Start-Process -FilePath "${{ steps.find_signtool.outputs.signtool_path }}" -ArgumentList "sign", "/fd", "SHA256", "/f", "artifacts/code-signing.pfx", "/p", "${{ secrets.CODE_SIGNING_CERTIFICATE_PASSWORD }}", "/t", "http://timestamp.digicert.com", "/v", $_.FullName -Wait
          }
        shell: pwsh

      - name: Upload Signed Installers
        uses: actions/upload-artifact@v4
        with:
          name: signed-rustdesk-installers
          path: artifacts/*.exe

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          tag_name: "v${{ needs.full_build_default.outputs.formatted_time }}"
          release_name: "Rustdesk Installer Release ${{ needs.full_build_default.outputs.formatted_time }}"
          body: "This release contains the signed Rustdesk installers."
          draft: false
          prerelease: false

      - name: Upload Signed Installers to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          upload_url: '${{ steps.create_release.outputs.upload_url }}'
          asset_path: artifacts/*.exe
          asset_name: rustdesk-setup.exe
          asset_content_type: application/octet-stream
