name: 0 - Full Rustdesk Build and Release

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  prep:
    uses: ./.github/workflows/prep.yml

  build:
    needs: prep
    uses: ./.github/workflows/build.yml

  sign:
    needs: build
    uses: ./.github/workflows/sign.yml

  release:
    needs: sign
    uses: ./.github/workflows/release.yml
