name: Prepare Environment

on:
  workflow_call:  # Only runs when called by another workflow

jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Get Chicago Timestamp
        id: timestamp
        run: |
          echo "formatted_time=$(date -d 'now' +'%Y.%m.%d.%H%M')" >> $GITHUB_ENV
          echo "formatted_time2=$(date -d 'now' +'%Y.%m.%d')" >> $GITHUB_ENV
          echo "formatted_time_linux=$(date -d 'now' +'%Y.%m.%d.%H%M')" >> $GITHUB_ENV

      - name: Upload Prep Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: prep-artifacts
          path: . # Adjust to include necessary files
