name: Release Rustdesk Installers

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Download Signed Installers
      - name: Download Signed Installers
        uses: actions/download-artifact@v4
        with:
          name: signed-rustdesk-installers
          path: release-artifacts

      # Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          tag_name: v${{ github.run_id }}
          release_name: "Rustdesk Installer Release ${{ github.run_id }}"
          body: "Signed Rustdesk installers."
          draft: false
          prerelease: false

      # Rename Signed Installers (ensure proper naming)
      - name: Rename Signed Installers
        shell: pwsh
        run: |
          Rename-Item -Path "release-artifacts/rustdesk-installer-default.exe" -NewName "rustdesk-setup.exe"
          Rename-Item -Path "release-artifacts/rustdesk-installer-jeff.exe" -NewName "rustdesk-setup-jeff.exe"

      # Upload Signed Default Installer to Release
      - name: Upload Signed Default Installer to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          upload_url: '${{ steps.create_release.outputs.upload_url }}'
          asset_path: release-artifacts/rustdesk-setup.exe
          asset_name: rustdesk-setup.exe
          asset_content_type: application/octet-stream

      # Upload Signed Jeff Build to Release
      - name: Upload Signed Jeff Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          upload_url: '${{ steps.create_release.outputs.upload_url }}'
          asset_path: release-artifacts/rustdesk-setup-jeff.exe
          asset_name: rustdesk-setup-jeff.exe
          asset_content_type: application/octet-stream
