name: Sign Rustdesk Installers

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  sign:
    runs-on: windows-latest
    steps:
      # Download Artifacts (Default Build)
      - name: Download Artifacts (Default Build)
        uses: actions/download-artifact@v4
        with:
          name: 'rustdesk-installer-default'
          path: artifacts

      # Download Artifacts (Jeff Build)
      - name: Download Artifacts (Jeff Build)
        uses: actions/download-artifact@v4
        with:
          name: 'rustdesk-installer-jeff'
          path: artifacts

      # Decode and Save Code Signing Certificate (from secrets)
      - name: Decode and Save Code Signing Certificate
        shell: bash
        run: |
          echo "${{ secrets.CODE_SIGNING_CERTIFICATE }}" | base64 -d > artifacts/code-signing.pfx

      # Locate signtool.exe
      - name: Locate signtool.exe
        id: find_signtool
        shell: pwsh
        run: |
          $signtoolPath = Get-ChildItem -Path "C:\Program Files (x86)\Windows Kits\10\bin\" -Recurse -Filter signtool.exe | 
            Where-Object { $_.FullName -match "x64" } | 
            Select-Object -First 1 -ExpandProperty FullName

          if (-not $signtoolPath) {
            Write-Host "ERROR: signtool.exe not found!"
            exit 1
          }

          echo "SIGNSUCCESS_PATH=$signtoolPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      # Sign Executables
      - name: Sign Executables
        env:
          CODE_SIGNING_CERTIFICATE_PASSWORD: '${{ secrets.CODE_SIGNING_CERTIFICATE_PASSWORD }}'
        shell: pwsh
        run: |
          Get-ChildItem -Path "artifacts" -Filter "*.exe" | ForEach-Object {
            & "${{ env.SIGNSUCCESS_PATH }}" sign /fd SHA256 /f "artifacts/code-signing.pfx" /p "$env:CODE_SIGNING_CERTIFICATE_PASSWORD" /t http://timestamp.digicert.com /v $_.FullName
          }

      # Upload Signed Installers
      - name: Upload Signed Installers
        uses: actions/upload-artifact@v4
        with:
          name: signed-rustdesk-installers
          path: artifacts/*.exe
